root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/server ."
  bin = "./tmp/server"
  delay = 1000 # ms
  exclude_dir = ["tmp"]
  include_ext = ["go", "html", "js"]
  exclude_regex = ["_test\\.go"]